var coolData = {
    "pageList": [{
            "id": 1,
            "type": "",
            "backgroundColor": "#27282a",
            "title": "\u7b2c1\u9875",
            "elementList": [{
                    "id": 6,
                    "type": "div",
                    "display": true,
                    "content": "<div class=\"element-last\" style=\"padding: 0px 5px; width: 100%; line-height: 1.25; font-size: 32px; cursor: default; word-break: break-all; word-wrap: break-word; writing-mode: inherit; min-height: inherit; opacity: 1;\">Demo012<\/div>",
                    "zIndex": 14,
                    "resize": 0,
                    "height": 46,
                    "width": 450,
                    "left": 478,
                    "top": 950,
                    "style": "color:#666;text-align:left;",
                    "animationList": [],
                    "displayName": "Demo012"
                }, {
                    "id": 5,
                    "type": "div",
                    "display": true,
                    "content": "<div class=\"element-last\" style=\"padding: 0px 5px; width: 100%; line-height: 1.25; font-size: 32px; cursor: default; word-break: break-all; word-wrap: break-word; writing-mode: inherit; min-height: inherit; opacity: 1;\"><span style=\"color: rgb(255, 255, 255); font-weight: bold; font-size: 20px;\">\u5929\u7fd4\u6d4b\u8bd5<\/span><\/div>",
                    "zIndex": 13,
                    "resize": 0,
                    "height": 47,
                    "width": 168,
                    "left": 508,
                    "top": 903,
                    "style": "color:#666;text-align:left;",
                    "animationList": [],
                    "displayName": "\u5929\u7fd4\u6d4b\u8bd5"
                }, {
                    "id": 1,
                    "type": "div",
                    "display": true,
                    "content": "<div class=\"element-last\" style=\"padding: 0px 5px; width: 100%; line-height: 1.25; font-size: 32px; cursor: default; word-break: break-all; word-wrap: break-word; writing-mode: inherit; min-height: inherit; opacity: 1;\"><span style=\"color: rgb(255, 255, 255); font-weight: bold;\">\u7b54\u9898\u6d4b\u8bd5demo<\/span><\/div>",
                    "zIndex": 10,
                    "resize": 0,
                    "height": 80,
                    "width": 285,
                    "left": 198,
                    "top": 288,
                    "style": "color:#666;text-align:left;",
                    "animationList": [],
                    "displayName": "\u7b54\u9898\u6d4b\u8bd5demo"
                }],
            "backgroundColorType": 1,
            "sort": 0,
            "backgroundImage": "2016\/10\/25\/1477376582781.jpg",
            "backgroundView": {
                "x": 48.477272727273,
                "y": 0,
                "width": 351.52272727273,
                "height": 604.1796875
            },
            "backgroundImageNaturalHeight": 711,
            "backgroundImageNaturalWidth": 400,
            "longPagebgMode": "1"
        }, {
            "id": 3,
            "type": "",
            "title": "\u7b2c3\u9875",
            "elementList": [{
                    "id": 11,
                    "type": "plugin",
                    "display": true,
                    "content": {
                        "token": "764095471ff59f4122f89dc44d2e0232",
                        "name": "\u7b54\u9898",
                        "coverImage": "g1\/2017\/10\/14\/1507943145503.png",
                        "price": "0.00",
                        "gold": 0,
                        "canUse": true,
                        "originalPrice": 0,
                        "originalGold": 0,
                        "canUseGold": "1",
                        "version": "10",
                        "isTop": "1",
                        "sideBar": "0",
                        "sizeType": "3",
                        "fixedWidth": "0",
                        "fixedHeight": "0",
                        "isUseLimit": "0",
                        "demoWsiteGuid": "rjcdqj",
                        "code": null,
                        "categoryId": "4",
                        "releaseTime": 1468553112,
                        "pos": "301",
                        "useCount": 162019,
                        "backgroundColor": "",
                        "backgroundImage": "2016\/07\/15\/1468554464852.jpg",
                        "levelId": null,
                        "canUseByDialog": false,
                        "$$hashKey": "object:279",
                        "gameVersion": 20,
                        "wsiteGuid": "n4tcc1",
                        "guid": "361829dd89196dd0c626b7dd009912e6",
                        "theme": {
                            "id": 0,
                            "name": "\u6807\u51c6",
                            "value": "default",
                            "list": [{
                                    "id": 13,
                                    "name": "\u5f39\u6846\u98ce\u683c",
                                    "value": "stylePage",
                                    "content": [{
                                            "id": 0,
                                            "value": "bg1",
                                            "text": "\u5f39\u6846\u80cc\u5f71\u8272",
                                            "backgroundColor": "#1D93FF"
                                        }],
                                    "type": "color"
                                }, {
                                    "id": 0,
                                    "name": "\u8fdb\u5ea6\u6837\u5f0f",
                                    "value": "progress",
                                    "type": "text",
                                    "width": 100,
                                    "height": 34,
                                    "backgroundColor": "",
                                    "content": [{
                                            "id": 0,
                                            "text": "\u8fdb\u5ea6\u6587\u5b57\u6837\u5f0f",
                                            "color": "#000000",
                                            "font_weight": "normal"
                                        }]
                                }, {
                                    "id": 20,
                                    "name": "\u5012\u8ba1\u65f6\u6837\u5f0f",
                                    "value": "downtime",
                                    "type": "text",
                                    "width": 100,
                                    "height": 34,
                                    "backgroundColor": "",
                                    "content": [{
                                            "id": 0,
                                            "text": "\u5012\u8ba1\u65f6\u6587\u5b57\u6837\u5f0f",
                                            "color": "#000000",
                                            "font_weight": "normal"
                                        }]
                                }, {
                                    "id": 1,
                                    "name": "\u9898\u76ee\u6837\u5f0f",
                                    "value": "question",
                                    "backgroundColor": "",
                                    "backgroundImage": "",
                                    "type": "text",
                                    "width": 640,
                                    "height": 0,
                                    "content": [{
                                            "id": 0,
                                            "text": "\u9898\u76ee\u6587\u5b57\u6837\u5f0f",
                                            "color": "#000000"
                                        }]
                                }, {
                                    "id": 2,
                                    "name": "\u9898\u76ee\u7b54\u6848\u6837\u5f0f",
                                    "value": "answer",
                                    "backgroundColor": "#e7e7e7",
                                    "backgroundImage": "",
                                    "type": "text",
                                    "content": [{
                                            "id": 0,
                                            "text": "\u9898\u76ee\u7b54\u6848\u6587\u5b57\u6837\u5f0f",
                                            "color": "#7e7e7e"
                                        }]
                                }, {
                                    "id": 3,
                                    "name": "\u9898\u76ee\u7b54\u6848\u6b63\u786e\u6837\u5f0f",
                                    "value": "answerRight",
                                    "backgroundColor": "#42D676",
                                    "backgroundImage": "",
                                    "type": "text",
                                    "content": [{
                                            "id": 0,
                                            "text": "\u9898\u76ee\u7b54\u6848\u6b63\u786e\u6587\u5b57\u6837\u5f0f",
                                            "color": "#FFFFFF"
                                        }]
                                }, {
                                    "id": 4,
                                    "name": "\u9898\u76ee\u7b54\u6848\u9519\u8bef\u6837\u5f0f",
                                    "value": "answerError",
                                    "backgroundColor": "#FF3940",
                                    "backgroundImage": "",
                                    "type": "text",
                                    "content": [{
                                            "id": 0,
                                            "text": "\u9898\u76ee\u7b54\u6848\u9519\u8bef\u6587\u5b57\u6837\u5f0f",
                                            "color": "#FFFFFF"
                                        }]
                                }, {
                                    "id": 5,
                                    "name": "\u56fe\u7247\u7b54\u6848\u6837\u5f0f",
                                    "value": "imageStyle",
                                    "src": "",
                                    "type": "image",
                                    "width": 170,
                                    "height": 170
                                }, {
                                    "id": 6,
                                    "name": "\u56fe\u7247\u7b54\u6848\u6b63\u786e\u6837\u5f0f",
                                    "value": "imageRightStyle",
                                    "backgroundImage": "",
                                    "backgroundColor": "rgba(66, 214, 118, 0.8)",
                                    "type": "text"
                                }, {
                                    "id": 7,
                                    "name": "\u56fe\u7247\u7b54\u6848\u9519\u8bef\u6837\u5f0f",
                                    "value": "imageErrorStyle",
                                    "backgroundImage": "",
                                    "backgroundColor": "rgba(255, 57, 64, 0.8)",
                                    "type": "text"
                                }, {
                                    "id": 8,
                                    "name": "\u58f0\u97f3\u9898\u76ee\u64ad\u653e\u56fe\u6807",
                                    "value": "imagePlay",
                                    "src": "https:\/\/assets.rrxh5.cc\/plugin\/764095471ff59f4122f89dc44d2e0232\/10\/assets\/play.png",
                                    "type": "image",
                                    "width": 130,
                                    "height": 130
                                }, {
                                    "id": 9,
                                    "name": "\u58f0\u97f3\u9898\u76ee\u6682\u505c\u56fe\u6807",
                                    "value": "imagePause",
                                    "src": "https:\/\/assets.rrxh5.cc\/plugin\/764095471ff59f4122f89dc44d2e0232\/10\/assets\/pause.png",
                                    "type": "image",
                                    "width": 130,
                                    "height": 130
                                }, {
                                    "id": 10,
                                    "name": "\u6b63\u786e\u97f3\u6548",
                                    "value": "audioRight",
                                    "src": "https:\/\/assets.rrxh5.cc\/plugin\/764095471ff59f4122f89dc44d2e0232\/10\/assets\/right.mp3",
                                    "type": "audio"
                                }, {
                                    "id": 11,
                                    "name": "\u9519\u8bef\u97f3\u6548",
                                    "value": "audioError",
                                    "src": "https:\/\/assets.rrxh5.cc\/plugin\/764095471ff59f4122f89dc44d2e0232\/10\/assets\/error.mp3",
                                    "type": "audio"
                                }, {
                                    "id": 12,
                                    "name": "\u901a\u5173\u97f3\u6548",
                                    "value": "audioPass",
                                    "src": "https:\/\/assets.rrxh5.cc\/plugin\/764095471ff59f4122f89dc44d2e0232\/10\/assets\/pass.mp3",
                                    "type": "audio"
                                }, {
                                    "id": 14,
                                    "name": "\u518d\u6765\u4e00\u6b21\u6309\u94ae\u56fe\u6807",
                                    "value": "imageReset",
                                    "src": "https:\/\/assets.rrxh5.cc\/plugin\/764095471ff59f4122f89dc44d2e0232\/10\/assets\/icon-reset.png",
                                    "type": "image",
                                    "width": 100,
                                    "height": 100
                                }, {
                                    "id": 15,
                                    "name": "\u6392\u884c\u699c\u6309\u94ae\u56fe\u6807",
                                    "value": "imageTop",
                                    "src": "https:\/\/assets.rrxh5.cc\/plugin\/764095471ff59f4122f89dc44d2e0232\/10\/assets\/icon-top.png",
                                    "type": "image",
                                    "width": 100,
                                    "height": 100
                                }, {
                                    "id": 16,
                                    "name": "\u5206\u4eab\u6309\u94ae\u56fe\u6807",
                                    "value": "imageShare",
                                    "src": "https:\/\/assets.rrxh5.cc\/plugin\/764095471ff59f4122f89dc44d2e0232\/10\/assets\/icon-share.png",
                                    "type": "image",
                                    "width": 100,
                                    "height": 100
                                }]
                        },
                        "rightColor": "#42D676",
                        "errorColor": "#FF3940",
                        "ruleContent": "\u8fd9\u662f\u4e00\u4e2a\u7b54\u9898demo",
                        "ruleType": 2,
                        "isCustomShare": "1",
                        "customShareTitle": "\u6211\u53c2\u4e0e\u4e86\u7b54\u9898\u6d3b\u52a8\uff0c\u5f97\u4e86#\u5206\u6570#\u5206\uff0c\u5feb\u6765\u6311\u6218\u6211\uff01",
                        "isFocusWx": "1",
                        "wxQr": "https:\/\/file2.rrxh5.cc\/g2\/c1\/2018\/05\/17\/1526525685863.jpg",
                        "answerVersion": 20,
                        "resultSettings": [{
                                "id": 0,
                                "minscore": 0,
                                "score": 59,
                                "gotoPageId": "next"
                            }, {
                                "id": 1,
                                "minscore": 60,
                                "score": 99,
                                "gotoPageId": "next"
                            }, {
                                "id": 2,
                                "minscore": 100,
                                "score": 100,
                                "gotoPageId": "next"
                            }, {
                                "id": 3,
                                "minscore": 101,
                                "score": "",
                                "gotoPageId": "next"
                            }, {
                                "id": 4,
                                "minscore": "",
                                "score": "",
                                "gotoPageId": "first"
                            }, {
                                "id": 5,
                                "minscore": "",
                                "score": "",
                                "gotoPageId": "first"
                            }, {
                                "id": 6,
                                "minscore": "",
                                "score": "",
                                "gotoPageId": "first"
                            }, {
                                "id": 7,
                                "minscore": "",
                                "score": "",
                                "gotoPageId": "first"
                            }],
                        "updateAssets": [{
                                "id": 0,
                                "name": "\u6807\u51c6",
                                "value": "default",
                                "list": [{
                                        "id": 13,
                                        "name": "\u5f39\u6846\u98ce\u683c",
                                        "value": "stylePage",
                                        "content": [{
                                                "id": 0,
                                                "value": "bg1",
                                                "text": "\u5f39\u6846\u80cc\u5f71\u8272",
                                                "backgroundColor": "#1D93FF"
                                            }],
                                        "type": "color"
                                    }, {
                                        "id": 0,
                                        "name": "\u8fdb\u5ea6\u6837\u5f0f",
                                        "value": "progress",
                                        "type": "text",
                                        "width": 100,
                                        "height": 34,
                                        "backgroundColor": "",
                                        "content": [{
                                                "id": 0,
                                                "text": "\u8fdb\u5ea6\u6587\u5b57\u6837\u5f0f",
                                                "color": "#000000",
                                                "font_weight": "normal"
                                            }]
                                    }, {
                                        "id": 20,
                                        "name": "\u5012\u8ba1\u65f6\u6837\u5f0f",
                                        "value": "downtime",
                                        "type": "text",
                                        "width": 100,
                                        "height": 34,
                                        "backgroundColor": "",
                                        "content": [{
                                                "id": 0,
                                                "text": "\u5012\u8ba1\u65f6\u6587\u5b57\u6837\u5f0f",
                                                "color": "#000000",
                                                "font_weight": "normal"
                                            }]
                                    }, {
                                        "id": 1,
                                        "name": "\u9898\u76ee\u6837\u5f0f",
                                        "value": "question",
                                        "backgroundColor": "",
                                        "backgroundImage": "",
                                        "type": "text",
                                        "width": 640,
                                        "height": 0,
                                        "content": [{
                                                "id": 0,
                                                "text": "\u9898\u76ee\u6587\u5b57\u6837\u5f0f",
                                                "color": "#000000"
                                            }]
                                    }, {
                                        "id": 2,
                                        "name": "\u9898\u76ee\u7b54\u6848\u6837\u5f0f",
                                        "value": "answer",
                                        "backgroundColor": "#e7e7e7",
                                        "backgroundImage": "",
                                        "type": "text",
                                        "content": [{
                                                "id": 0,
                                                "text": "\u9898\u76ee\u7b54\u6848\u6587\u5b57\u6837\u5f0f",
                                                "color": "#7e7e7e"
                                            }]
                                    }, {
                                        "id": 3,
                                        "name": "\u9898\u76ee\u7b54\u6848\u6b63\u786e\u6837\u5f0f",
                                        "value": "answerRight",
                                        "backgroundColor": "#42D676",
                                        "backgroundImage": "",
                                        "type": "text",
                                        "content": [{
                                                "id": 0,
                                                "text": "\u9898\u76ee\u7b54\u6848\u6b63\u786e\u6587\u5b57\u6837\u5f0f",
                                                "color": "#FFFFFF"
                                            }]
                                    }, {
                                        "id": 4,
                                        "name": "\u9898\u76ee\u7b54\u6848\u9519\u8bef\u6837\u5f0f",
                                        "value": "answerError",
                                        "backgroundColor": "#FF3940",
                                        "backgroundImage": "",
                                        "type": "text",
                                        "content": [{
                                                "id": 0,
                                                "text": "\u9898\u76ee\u7b54\u6848\u9519\u8bef\u6587\u5b57\u6837\u5f0f",
                                                "color": "#FFFFFF"
                                            }]
                                    }, {
                                        "id": 5,
                                        "name": "\u56fe\u7247\u7b54\u6848\u6837\u5f0f",
                                        "value": "imageStyle",
                                        "src": "",
                                        "type": "image",
                                        "width": 170,
                                        "height": 170
                                    }, {
                                        "id": 6,
                                        "name": "\u56fe\u7247\u7b54\u6848\u6b63\u786e\u6837\u5f0f",
                                        "value": "imageRightStyle",
                                        "backgroundImage": "",
                                        "backgroundColor": "rgba(66, 214, 118, 0.8)",
                                        "type": "text"
                                    }, {
                                        "id": 7,
                                        "name": "\u56fe\u7247\u7b54\u6848\u9519\u8bef\u6837\u5f0f",
                                        "value": "imageErrorStyle",
                                        "backgroundImage": "",
                                        "backgroundColor": "rgba(255, 57, 64, 0.8)",
                                        "type": "text"
                                    }, {
                                        "id": 8,
                                        "name": "\u58f0\u97f3\u9898\u76ee\u64ad\u653e\u56fe\u6807",
                                        "value": "imagePlay",
                                        "src": "https:\/\/assets.rrxh5.cc\/plugin\/764095471ff59f4122f89dc44d2e0232\/10\/assets\/play.png",
                                        "type": "image",
                                        "width": 130,
                                        "height": 130
                                    }, {
                                        "id": 9,
                                        "name": "\u58f0\u97f3\u9898\u76ee\u6682\u505c\u56fe\u6807",
                                        "value": "imagePause",
                                        "src": "https:\/\/assets.rrxh5.cc\/plugin\/764095471ff59f4122f89dc44d2e0232\/10\/assets\/pause.png",
                                        "type": "image",
                                        "width": 130,
                                        "height": 130
                                    }, {
                                        "id": 10,
                                        "name": "\u6b63\u786e\u97f3\u6548",
                                        "value": "audioRight",
                                        "src": "https:\/\/assets.rrxh5.cc\/plugin\/764095471ff59f4122f89dc44d2e0232\/10\/assets\/right.mp3",
                                        "type": "audio"
                                    }, {
                                        "id": 11,
                                        "name": "\u9519\u8bef\u97f3\u6548",
                                        "value": "audioError",
                                        "src": "https:\/\/assets.rrxh5.cc\/plugin\/764095471ff59f4122f89dc44d2e0232\/10\/assets\/error.mp3",
                                        "type": "audio"
                                    }, {
                                        "id": 12,
                                        "name": "\u901a\u5173\u97f3\u6548",
                                        "value": "audioPass",
                                        "src": "https:\/\/assets.rrxh5.cc\/plugin\/764095471ff59f4122f89dc44d2e0232\/10\/assets\/pass.mp3",
                                        "type": "audio"
                                    }, {
                                        "id": 14,
                                        "name": "\u518d\u6765\u4e00\u6b21\u6309\u94ae\u56fe\u6807",
                                        "value": "imageReset",
                                        "src": "https:\/\/assets.rrxh5.cc\/plugin\/764095471ff59f4122f89dc44d2e0232\/10\/assets\/icon-reset.png",
                                        "type": "image",
                                        "width": 100,
                                        "height": 100
                                    }, {
                                        "id": 15,
                                        "name": "\u6392\u884c\u699c\u6309\u94ae\u56fe\u6807",
                                        "value": "imageTop",
                                        "src": "https:\/\/assets.rrxh5.cc\/plugin\/764095471ff59f4122f89dc44d2e0232\/10\/assets\/icon-top.png",
                                        "type": "image",
                                        "width": 100,
                                        "height": 100
                                    }, {
                                        "id": 16,
                                        "name": "\u5206\u4eab\u6309\u94ae\u56fe\u6807",
                                        "value": "imageShare",
                                        "src": "https:\/\/assets.rrxh5.cc\/plugin\/764095471ff59f4122f89dc44d2e0232\/10\/assets\/icon-share.png",
                                        "type": "image",
                                        "width": 100,
                                        "height": 100
                                    }]
                            }],
                        "randomAnswer": {
                            "show": false,
                            "count": 10,
                            "answerCount": "2",
                            "showResult": false,
                            "totalLimitTime": 300,
                            "showLimitTime": false,
                            "showLimitTimeType": 1
                        },
                        "questionVersion": 20,
                        "questionType": 3,
                        "isShowScore": true
                    },
                    "zIndex": 10003,
                    "resize": 0,
                    "height": 1010,
                    "width": 640,
                    "left": 0,
                    "top": 0,
                    "style": "",
                    "animationList": [],
                    "displayName": "\u63d2\u4ef6-\u7b54\u9898"
                }],
            "pageType": 1,
            "backgroundColor": "#ffffff",
            "backgroundColorType": 1,
            "bgGradien": {
                "bgColor": "",
                "gradientClassName": ""
            },
            "sort": 1,
            "height": 1010,
            "percent": 0.75,
            "longPagebgMode": "1",
            "backgroundImage": "",
            "backgroundView": {
                "x": 0,
                "y": 0,
                "width": 640
            },
            "backgroundImageNaturalHeight": 514,
            "backgroundImageNaturalWidth": 508
        }, {
            "id": 5,
            "type": "",
            "title": "\u7b2c5\u9875",
            "elementList": [{
                    "id": 13,
                    "type": "div",
                    "display": true,
                    "content": "<div class=\"element-last\" style=\"padding: 0px 5px; width: 100%; line-height: 1.25; font-size: 32px; cursor: default; word-break: break-all; word-wrap: break-word; writing-mode: inherit; min-height: inherit; opacity: 1;\">\u7ed3\u679c\u9875\u9762<\/div>",
                    "zIndex": 10,
                    "resize": 0,
                    "height": 46,
                    "width": 450,
                    "left": 214,
                    "top": 255,
                    "style": "color:#666;text-align:left;",
                    "animationList": [],
                    "displayName": "\u7ed3\u679c\u9875\u9762"
                }],
            "pageType": 1,
            "backgroundColor": "#ffffff",
            "backgroundColorType": 1,
            "bgGradien": {
                "bgColor": "",
                "gradientClassName": ""
            },
            "sort": 2,
            "height": 1010,
            "percent": 0.75,
            "backgroundImage": "2016\/10\/25\/1477376587741.jpg",
            "backgroundView": {
                "x": 0,
                "y": 11.75,
                "width": 400,
                "height": 687.5
            },
            "backgroundImageNaturalHeight": 711,
            "backgroundImageNaturalWidth": 400
        }],
    "result": 0,
    "msg": "ok",
    "lastPageGoto": "stop",
    "guid": "n4tcc1",
    "title": "\u4eba\u4eba\u79c0\u6d4b\u8bd5Demo",
    "describe": "\u5929\u7fd4\u6d4b\u8bd5",
    "shareImageUrl": "g2\/c1\/2018\/05\/17\/1526525685863.jpg",
    "musicUrl": "g2\/c1\/2018\/05\/17\/1526526673996.mp3",
    "musicPlayIcon": "",
    "musicStopIcon": "",
    "musicPosition": "rt",
    "flipWay": "down",
    "flipAnimation": "110",
    "cssList": [],
    "musicTitle": "\u5c0f\u702c\u6751\u6676 - Truth",
    "musicAutoPlay": true,
    "llImageUrl": "",
    "llColor": "#25a7fb",
    "aboutBgUrl": "",
    "pricedPluginCount": null,
    "flipProgress": "1",
    "copyright": {
        "from": "bottom",
        "content": "\u514d\u8d39\u5236\u4f5c \u2192 \u4eba\u4eba\u79c0",
        "textAlign": "right",
        "url": "http:\/\/mp.weixin.qq.com\/s?__biz=MzA4ODc5OTE1OQ==&mid=403178211&idx=1&sn=9c50c942df41020d626d50289a75cf16#rd",
        "color": "#fff",
        "bgColor": "#000"
    },
    "copyrightPage": null,
    "showCustomLoadingLogo": false,
    "showVisitCount": true,
    "sharePosterBgImg": null,
    "showShareCount": null,
    "showShareNickname": null,
    "danmuLike": {
        "show": true,
        "showDanmu": true,
        "review": false,
        "style": "horizontal"
    },
    "focusWechat": {
        "show": false,
        "name": "\u4eba\u4eba\u79c0",
        "qrcode": "rrx-qrcode.jpg",
        "describe": "\u79fb\u52a8\u7aef\u4e92\u52a8\u8425\u9500\u7ba1\u5bb6",
        "icon": "focus-icon.png"
    },
    "showReport": true,
    "topMenu": {
        "show": "0",
        "icon": "topmenu-icon2.png",
        "list": [{
                "id": 1,
                "name": "\u83dc\u53551",
                "type": "page",
                "value": 0
            }]
    },
    "forbidShare": 0
};